Add flush option

diff --git a/log b/log
--- a/log
+++ b/log
@@ -29,6 +29,11 @@ trim_log() {
 	log "logfile cut"
 }
 
+flush() {
+	rm ~/var/log || err "Could not flush logfile" || exit 1
+	log_mesg "Log file flushed."
+}
+
 usage() {
 	echo "log - log a message to ~/var/log"
 	echo "usage: log [ -h | --help ] [ --show ] [ MSG ]"
@@ -37,6 +42,7 @@ usage() {
 	echo "	--show			show the last 10 logs"
 	echo "	--show LINES		show the last LINES logs"
 	echo "	--cut			cut log file 500 lines"
+	echo "	--flush			clear all lines from file"
 	exit 0
 }
 
@@ -45,10 +51,10 @@ usage() {
 while true; do
 	case $1 in
 		-*) case $1 in
-			"--show")	show_log "$2" && shift;
-					shift;;
-			"-h"|"--help")	usage;;
-			"--cut")	trim_log; shift;;
+			"--show")	show_log "$2" && shift;		shift;;
+			"-h"|"--help")	usage;				shift;;
+			"--cut")	trim_log;			shift;;
+			"--flush")	flush;				shift;;
 			*)		err "unknown option: $1" || exit 1;;
 		esac;;
 		*) break;;
