I'll work on this more later

diff --git a/SCP b/SCP
--- a/SCP
+++ b/SCP
@@ -1,44 +1,37 @@
 #!/bin/sh
 
-# Usage check
+# Declarations
+DOCPATH="$HOME/Documents/SCP"
+SELF="$(basename "$0")"
+
+# Functions
+
+# Utils
+err() { echo "${SELF}: error: $@" 1>&2 ; }
+die() { err "FATAL ERROR: $@" ; exit 1 ; }
+
+# Usage
 usage() {
 	echo "	SCP - Fetch Secure Contain Protect Foundation Documents"
 	echo "	usage: SCP [ OPTIONS ... ] DOCUMENT"
 	echo "	options:"
 	echo "		-h	--help	show this message"
-	echo "		-l	--less	show document in less instead of stdout"
-	echo "		-s	--save	save document locally"
-	echo "	"
-	echo "	DOCUMENT  is  the  SCP-ID  of  the document to display. It may be"
-	echo "	either a valid SCP ID, 'all' or  'ALL'.  A  valid ID is a decimal"
-	echo "	number of three or more digits corecponding  to  an SCP Document,"
-	echo "	SCP IDs less than 1000 (one thousand) should have the appropriate"
-	echo "	number of 0s (zeros) prepended."
+
 	exit 0
 }
 
-[ $# -gt 0 ] || usage
-
-# Declarations
-DOCPATH="$HOME/Documents/SCP"
-LESSDOC="FALSE"
-SAVEDOC="FALSE"
-
-# Functions
 fetchDocument() {
-	# download formated document and cut pre and post
-	lynx -dump "http://scp-wiki.wikidot.com/scp-$1" | sed -n '/IFRAME/,$p' | tail -n +4 | sed -n '/page revision/q;p'
+	# download formatted document and cut pre and post
+	[ -x "$(command -v w3m)" ] || die "w3m is not installed"
+	w3m -dump "http://scp-wiki.wikidot.com/scp-$1"
 }
 
 getDocumentSCP() {
-	# if save TRUE fetch to file in DOCPATH
-	# if save TRUE cat file else fetch
-	# if less TRUE cat/fetch and pipe through less
-	fetchDocument $1
+	fetchDocument "$1"
 }
 
 readDocumentSCP() {
-	espeak -f scp-$1 -w scp-$1.wav
+	espeak -f "scp-$1" -w "scp-$1.wav"
 }
 
 showDocumentSCP() {
@@ -46,54 +39,50 @@ showDocumentSCP() {
 
 	case "$1" in
 		"all"|"ALL")
-			for ID in $(getAllDocumentIds); do
-				getDocumentSCP $ID
+			for ID in $(getAllDocumentIds)
+			do
+				getDocumentSCP "$ID"
 			done
 			;;
 		*)
-			getDocumentSCP $1
+			getDocumentSCP "$1"
 			;;
 	esac
 }
 
 getAllDocumentIds() {
-	# outer loop, nest at will
-	for l in "" 1 2 3 4 5 6 7 8 9; do
-
-		# inner loop, 0 padded to 3 digits
-		for k in 0 1 2 3 4 5 6 7 8 9; do
-			for j in 0 1 2 3 4 5 6 7 8 9; do
-				for i in 0 1 2 3 4 5 6 7 8 9; do
+	# 0 padded to 3 digits
+	for l in "" 1 2 3 4 5 6 7 8 9
+	do
+		for k in 0 1 2 3 4 5 6 7 8 9
+		do
+			for j in 0 1 2 3 4 5 6 7 8 9
+			do
+				for i in 0 1 2 3 4 5 6 7 8 9
+				do
 					echo "$l$k$j$i"
 				done
 			done
-		done | tail -n+2
-
+		done | tail -n +2
 	done
 }
 
 main() {
-	while [ $# -gt 0 ] ; do
-		case $1 in
+	[ "$#" -gt 0 ] || usage
+
+	while [ "$#" -gt 0 ]
+	do
+		case "$1" in
 			-h|--help)
-				shift
 				usage
-				;;
-			-l|--less)
-				shift
-				LESSDOC="TRUE"
-				;;
-			-s|--save)
-				shift
-				SAVEDOC="TRUE"
 				;;
 			*)
 				showDocumentSCP "$1"
-				shift
 				;;
 		esac
+		shift
 	done
 }
 
-main "$@"
+main $@
 
